on:
  push:
    tags:
      - 'v*'

name: Create release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-release-${{ hashFiles('**/Cargo.lock') }}
    - name: Build
      run: cargo build --release
    - name: Create Release
      id: create_release
      uses: ncipollo/release-action@v1
      with:
        artifacts: target/release/bot-ticelli
        generateReleaseNotes: true
